
version: "3.3"

services:
  spotify_clone:
    container_name: music_player
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ".:/app"
      - "/app/node_modules"
    env_file: .env
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true